### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Tropicalista** [coldbox-modules/cbfs#2]
I'm trying to install this trough commandbox, but always got this message:

```
 Aww man,  forgebox isn't feeling well.
 Error getting ForgeBox entry [cbfs]  The entry slug sent is invalid or do
 es not exist
```
Is this published or not?

**Comment by elpete** [comment]
This is not published, sadly. Our attention has been pulled elsewhere. Any help you’d like to contribute is welcome. There’s an `AbstractDiskSpec` you can extend in your concrete test to verify it works. I do think that it is missing some tests still.

**Comment by Tropicalista** [comment]
Yes, I realized later that is a work in progress.

I'm trying to port to coldbox module [this package](https://github.com/alexusmai/laravel-file-manager) and suddenly I discovered something that I could use.

Unfortunately isn't really clear to me how this is supposed to work.

The provider must implements IDisk interface?

So all those functions are missing in local provider?

The MockProvider is a starting point?

**Comment by elpete** [comment]
I think I was the last one to touch this repo and all my work was on setting up the `AbstractDiskSpec` and the `MockProvider`.  Any other providers would need to implement `IDisk`.

We’re disappointed that this isn’t ready as well. Too many modules to make. Maybe I’ll be back after Quick 3.0.0. (Who am I kidding. It will at least be Quick 3.0.1. 😉)
