### ISSUE TITLE
Introduce a File object and proxy method calls to the disk to provide a more fluent API

### ISSUE THREAD

**Issue by grantcopley** [coldbox-modules/cbfs#25]
When working with CBFS in it’s current form, you are constantly referencing the storage object and passing around a file path to all the methods.

For example:

```
var storage = cbfs().get( "local" );
var file = storage.create( "path/to/file.txt", "some contents" );

storage.append( "path/to/file.txt", "more contents" );
storage.copy( "path/to/file.txt", "some_other_file.txt" );
```

Introducing a File object would clean up the API calls considerably and wouldn’t require much to refactor if we simply proxy the calls to the disk.

```
// create() would return a File Object
var storage = cbfs().get( "local" );
var file = storage
  .create( "path/to/file.txt", "contents" )
  .append( "more contents" )
  .copy( "some_other_file.txt" );
  
// Other methods become easier also
file.size();
file.getAsBinary();
file.delete();
```

**Comment by jclausen** [comment]
The `get()` method will return either binary or text, depending on the mimeType.  `getAsBinary` should not be necessary as a method.
