### ISSUE TITLE
Error in test

### ISSUE THREAD

**Issue by Tropicalista** [coldbox-modules/cbfs#3]
This should be `directoryPath` and **not** `filePath` to make this test have sense. Or am I missing something?

https://github.com/coldbox-modules/cbfs/blob/bd2751d00f0581a9c15b7bef2df78f0eff89f84f/test-harness/tests/resources/AbstractDiskSpec.cfc#L67

**Comment by elpete** [comment]
I think it works either way. There is no data when the test starts. The delete call is for disks that may need to clean up. If delete can take a directory that would work as well.

**Comment by Tropicalista** [comment]
But if I delete filePath, why I should expect that directoryPath should not exists?
I can delete a file and directory stay where is it!!! 
```
                it( "can verify a directory exists", function() {
                    var disk = getDisk();
                    var filePath = "/one/two/test_file.txt";
                    var directoryPath = "/one/two/";
                    disk.delete( filePath );
                    expect( disk.exists( directoryPath ) )
                        .toBeFalse( "#directoryPath# should not exist" );
                    disk.create( filePath, "my contents" );
                    expect( disk.exists( directoryPath ) )
                        .toBeTrue( "#directoryPath# should exist" );
                } );

```

**Comment by elpete** [comment]
Hmmm...you make a good point.  I'm not sure why I wrote it that way. :sweat_smile:
